function(d2bs_extract_version)
  file(READ "${CMAKE_SOURCE_DIR}/d2bs/src/version.h" file_contents)
  string(REGEX MATCH "D2BS_VER_MAJOR = ([0-9]+)" _ "${file_contents}")
  if(NOT CMAKE_MATCH_COUNT EQUAL 1)
    message(FATAL_ERROR "Could not extract major version number from d2bs/version.h")
  endif()
  set(ver_major ${CMAKE_MATCH_1})
  
  string(REGEX MATCH "D2BS_VER_MINOR = ([0-9]+)" _ "${file_contents}")
  if(NOT CMAKE_MATCH_COUNT EQUAL 1)
    message(FATAL_ERROR "Could not extract minor version number from d2bs/version.h")
  endif()
  
  set(ver_minor ${CMAKE_MATCH_1})
  string(REGEX MATCH "D2BS_VER_PATCH = ([0-9]+)" _ "${file_contents}")
  if(NOT CMAKE_MATCH_COUNT EQUAL 1)
    message(FATAL_ERROR "Could not extract patch version number from d2bs/version.h")
  endif()
  set(ver_patch ${CMAKE_MATCH_1})
  
  set(D2BS_VERSION_MAJOR ${ver_major} PARENT_SCOPE)
  set(D2BS_VERSION_MINOR ${ver_minor} PARENT_SCOPE)
  set(D2BS_VERSION_PATCH ${ver_patch} PARENT_SCOPE)
  set(D2BS_VERSION "${ver_major}.${ver_minor}.${ver_patch}" PARENT_SCOPE)
endfunction()
